openapi: 3.0.0
info:
  title: for-serverless-hello-telegram-bot
  version: 1.0.0
paths:
  /sayhello.png:
    get:
      x-yc-apigateway-integration:
        type: object-storage
        bucket: for-serverless-hello-telegram-bot
        object: sayhello.png
        presigned_redirect: false
        service_account: IDYOURACCOUNT
      operationId: static